config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: "questions#index"

  concern :voted do
    member do
      post :like
      post :dislike
      delete :cancel
    end
  end

  concern :commented do
    member do
      post :comment
    end
  end

  resources :questions, concerns: %i[voted commented] do
    resources :subscriptions, shallow: true, only: %i[create destroy]
    resources :answers, concerns: %i[voted commented], shallow: true, only: %i[create update destroy] do
      patch :mark_as_best, on: :member
    end
  end

  resources :files, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :rewards, only: %i[index]

  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me, on: :collection
        get :others, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        get :answers, on: :member
        resources :answers, shallow: true, only: %i[show create update destroy]
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/views/shared/_comment_form.html.slim
- if policy(commentable).comment?
  = link_to 'Add comment', @comment, class: 'new-comment', data: { commentable_id: commentable.id }

  = form_with scope: :comment, url: polymorphic_path(commentable, action: 'comment'), class: 'hidden',
          html: { id: "new-comment-#{commentable.id}" }, local: false, data: { type: :json } do |f|
    = f.label :body, 'Your comment'
    = f.text_area :body

    = f.submit 'Save Comment', class: 'btn btn-info btn-sm'

app/views/shared/_comments.html.slim
div class="comments-#{commentable.id}"
  ul
    - commentable.comments.each do |comment|
      - cache comment do
        li =comment.body

  .comments-errors

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_files.html.slim
div class="files-#{resource.files.first.record_id}"
p Files:
ul
  - resource.files.each do |file|
    li id="file-#{file.id}"
      = link_to file.filename.to_s, url_for(file)

      - if policy(resource).destroy?
        = link_to 'Delete attachment', file_path(file.id), method: :delete

app/views/shared/_flash_js.js.erb
$('.flashes').empty();
$('.flashes').replaceWith('<%= render partial: 'shared/flashes', locals: { flash: flash } %>');

app/views/shared/_flashes.html.slim
.flashes
  - flash.each do |key, value|
    p= value

app/views/shared/_links.html.slim
div class="links-#{links.first.linkable.id}"
  p Links:
  ul
    - links.each do |link|
      li id="link-#{link.id}"
        - if link.gist?
          div data-gist = "#{link.url}" = link_to link.url
        - else
          = link_to link.name, link.url

        - if current_user&.author_of?(link.linkable)
          = link_to 'Delete link', link_path(link), remote: true, method: :delete, class: 'inline-block border border-red-500 rounded py-1 px-3 bg-red-500 text-white top-0 right-0'

app/views/shared/_links_fields.html.slim
.nested-fields
  .field
    = f.label :name, 'Link name', class: 'block mb-2 text-sm font-medium text-gray-900'
    = f.text_field :name, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5'

  .field
    = f.label :url, class: 'block mb-2 text-sm font-medium text-gray-900'
    = f.text_field :url, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5'

  = link_to_remove_association 'remove link', f, class: 'text-white bg-blue-700 font-medium rounded-lg text-xs px-5 py-2.5 mr-2 mb-2'

app/views/shared/_navigation.html.slim
nav class='bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-800'
  div class='container flex flex-wrap justify-between items-center mx-auto'
    span class='self-center text-xl font-semibold whitespace-nowrap dark:text-white' Thinknetica-QnA
    div class='w-full md:block md:w-auto'
      ul class='flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium'
        - if user_signed_in?
          li
            = link_to 'Questions', questions_path, class: 'block py-2 pr-4 pl-3 text-white rounded p-0 md:p-0'
          li
            = link_to 'Rewards', rewards_path, class: 'block py-2 pr-4 pl-3 text-white rounded p-0 md:p-0'
          li
            = link_to 'LogOut', destroy_user_session_path, method: :delete, class: 'log_out text-white bg-red-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3'
        - else
          li
            = link_to 'Registration', new_user_registration_path, class: 'registration text-white bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3'
          li
            = link_to 'Login', new_user_session_path, class: 'login text-white bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3'

app/views/shared/_subscribe.html.slim
.subscription
  - if current_user
    - if subscription.nil? || policy(subscription).create?
      = link_to 'Subscribe to new answers', question_subscriptions_path(question), method: :post, remote: true,
              data: { type: :js }, class: 'subscribe-button'

    - if !subscription.nil? && policy(subscription).destroy?
      = link_to 'Unsubscribe', subscription_path(subscription), method: :delete, remote: true,
              data: { type: :js }, class: 'unsubscribe-button'

app/views/shared/_votes.html.slim
div class="votes-#{votable.id}"
  p class='votes' Votes: #{votable.rating || 0}
  - if policy(votable).like?
    .vote
      = link_to 'Like', polymorphic_path(votable, action: :like), method: :post, remote: true,
              data: { type: :json }, class: (policy(votable).like? ? 'like-button' : 'like-button hidden')
      = link_to 'Dislike', polymorphic_path(votable, action: :dislike), method: :post, remote: true,
              data: { type: :json }, class: (policy(votable).like? ? 'dislike-button' : 'dislike-button hidden')
      = link_to 'Cancel', polymorphic_path(votable, action: :cancel), method: :delete, remote: true,
              data: { type: :json }, class: (policy(votable).cancel? ? 'cancel-button' : 'cancel-button hidden')